name: Actions Workflow

on:
  repository_dispatch:
    types: [build]
  push:
  pull_request: :
   types: [closed,assigned,opened,reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: | 
          ls
          pwd
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
      - name: Checkout
        uses: actions/checkout@v1
      - name: list after checkout
        run: |
          pwd
          ls -a

      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1 #version or #commit id #branch
        with:
          who-to-greet: 'Min Myat Oo'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
