name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!" #Bash Shell
      - name: multiline script
        run: |
          node -v
          npm -v

